parameters:
    env(WS_SLUG_HISTORY_STORAGE): 'CACHE'
    ws_slug_history.storage: '%env(WS_SLUG_HISTORY_STORAGE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    Wisoft\SlugHistoryBundle\:
        resource: "../src/"
        exclude:
          - ../src/Attribute
          - ../src/SlugHistoryBundle.php
  
    Wisoft\SlugHistoryBundle\EventListener\DoctrineSlugListener:
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }
    
    ws_slug_history.cache_slug_storage:
        class: Wisoft\SlugHistoryBundle\Service\Storage\CacheSlugStorage
        autowire: true
    #     arguments:
    #         $cache: '@cache.app'
    
    ws_slug_history.database_slug_storage:
        class: Wisoft\SlugHistoryBundle\Service\Storage\DatabaseSlugStorage
        autowire: true
        autoconfigure: true
    #     arguments:
    #         $em: '@doctrine.orm.entity_manager'

    Wisoft\SlugHistoryBundle\Service\Manager\SlugManager:
        autowire: true
        arguments:
            $storageInterface: '@=parameter("ws_slug_history.storage") matches "/^database$/i" ? service("ws_slug_history.database_slug_storage") : service("ws_slug_history.cache_slug_storage")'