parameters:
    env(WISYMFONY_SLUG_HISTORY_STORAGE): 'CACHE'
    wisymfony_slug_history.storage: '%env(WISYMFONY_SLUG_HISTORY_STORAGE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    Wisymfony\SlugHistoryBundle\:
        resource: "../src/"
        exclude:
          - ../src/Attribute
          - ../src/SlugHistoryBundle.php
  
    Wisymfony\SlugHistoryBundle\EventListener\DoctrineSlugListener:
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }
    
    wisymfony_slug_history.cache_slug_storage:
        class: Wisymfony\SlugHistoryBundle\Service\Storage\CacheSlugStorage
        autowire: true
        autoconfigure: true
        arguments:
            $cache: '@cache.app'
    
    wisymfony_slug_history.database_slug_storage:
        class: Wisymfony\SlugHistoryBundle\Service\Storage\DatabaseSlugStorage
        autowire: true
        autoconfigure: true
        arguments:
            $em: '@doctrine.orm.entity_manager'

    Wisymfony\SlugHistoryBundle\Service\Manager\SlugManager: ~